---
title: "Home"
output:
   html_document:
    toc: false
    code_folding: null
    number_sections: false
    theme: "cerulean"
---


## Coral genetics workshop for conservation and restoration  
#### Building capacity for genetic analysis to support coral reef restoration in Costa Rica

EN: On July 18 – 21, 2022, Raising Coral Costa Rica [(RCCR)](https://www.raisingcoral.org/) will collaborate with scientists from the University of Costa Rica (UCR) and the Smithsonian Tropical Research Institute (STRI) to host a conservation genetics workshop at the UCR campus in San José. The workshop will provide training in molecular biology laboratory techniques and data analysis methods for genetic identification of marine invertebrates (with an emphasis on reef-building corals in the genus *Pocillopora*), and is being offered to research faculty, advanced undergraduate and graduate-level students. The workshop will offer training to 7 Costa Rican students and 4 international students from other Latin American countries and will take place in two sessions: first, an in-person laboratory training workshop in July 2022, followed by a virtual bioinformatics data analysis workshop later in 2022. This project will generate data for a project assessing the genetic diversity of *Pocillopora* corals in restoration nurseries and wild populations in Costa Rica, while providing practical training in molecular laboratory skills and bioinformatics analysis methods in a real research context. We hope that this workshop will engage diverse coral conservationists in Costa Rica and throughout Latin America to increase collaboration, and that the students in the workshop are able to apply the genetics techniques they learn to other *Pocillopora* coral restoration projects across the eastern Pacific region!



## Taller genética de corales para la conservación y restauración
#### Creación de capacidad nacional para el análisis genético de corales con fines de restauración y conservación de arrecifes coralinos en Costa Rica

ES: Del 18 al 21 de julio de 2022, Raising Coral Costa Rica [(RCCR)](https://www.raisingcoral.org/) colaborará con científicos de la Universidad de Costa Rica (UCR) y el Instituto Smithsonian de Investigaciones Tropicales (STRI) para albergar un taller de genética de la conservación en el campus de la UCR en San José. El taller brindará capacitación en técnicas de laboratorio de biología molecular y métodos de análisis de datos para la identificación genética de invertebrados marinos (con énfasis en los corales formadores de arrecifes del género *Pocillopora*), y se ofrece a profesores de investigación, estudiantes avanzados de pregrado y posgrado. El taller ofrecerá capacitación a 7 estudiantes costarricenses y 4 estudiantes internacionales de otros países de América Latina y se llevará a cabo en dos sesiones: primero, un taller de capacitación de laboratorio presencial en julio de 2022, seguido de un taller virtual de análisis de datos de bioinformática más adelante en 2022. Este proyecto generará datos para un proyecto que evalúa la diversidad genética de los corales Pocillopora en viveros de restauración y poblaciones silvestres en Costa Rica, al tiempo que brinda capacitación práctica en habilidades de laboratorio molecular y métodos de análisis bioinformático en un contexto real de investigación. ¡Esperamos que este taller involucre a diversos conservacionistas de coral en Costa Rica y en toda América Latina para aumentar la colaboración, y que los estudiantes en el taller puedan aplicar las técnicas genéticas que aprenden a otros proyectos de restauración de coral *Pocillopora* en la región del Pacífico oriental!


