---
title: "References"
output:
   html_document:
    toc: true
    code_folding: null
    number_sections: false
    theme: "cerulean"
---

***

### Papers to read for background information  

* [The mitochondrial genome of Pocillopora (Cnidaria: Scleractinia) contains two variable regions: The putative D-loop and a novel ORF of unknown function](https://www.sciencedirect.com/science/article/abs/pii/S0378111907003666?via%3Dihub)  

* [Blind to morphology: genetics identifies several widespread ecologically common species and few endemics among Indo‐Pacific cauliflower corals (Pocillopora, Scleractinia)](https://onlinelibrary.wiley.com/doi/10.1111/jbi.12110)  

* [Slow mitochondrial DNA sequence evolution in the Anthozoa (Cnidaria)](https://onlinelibrary.wiley.com/doi/full/10.1046/j.1365-294X.2002.01652.x)

* [No variation and low synonymous substitution rates in coral mtDNA despite high nuclear variation](https://bmcecolevol.biomedcentral.com/articles/10.1186/1471-2148-6-24)

* [Phylogenomics, Origin, and Diversification of Anthozoans (Phylum Cnidaria)](https://doi.org/10.1093/sysbio/syaa103)

* [Computational Characterization of the mtORF of Pocilloporid Corals: Insights into Protein Structure and Function in Stylophora Lineages from Contrasting Environments](https://www.mdpi.com/2073-4425/10/5/324)

* [Patterns of genetic structure among Hawaiian corals of the genus Pocillopora yield clusters of individuals that are compatible with morphology](https://doi.org/10.1016/j.crvi.2007.12.003)

* [Haplowebs as a graphical tool for delimiting species: a revival of Doyle's "field for recombination" approach and its application to the coral genus Pocillopora in Clipperton](https://bmcecolevol.biomedcentral.com/articles/10.1186/1471-2148-10-372) 

* [Extreme phenotypic polymorphism in the coral genus Pocillopora; micro-morphology corresponds to mitochondrial groups, while colony morphology does not](https://doi.org/10.5343/bms.2012.1080)

* [New evidence shows that Pocillopora ‘damicornis-like’ corals in Singapore are actually Pocillopora acuta](https://bdj.pensoft.net/articles.php?id=11407)

* [Rarity of the “common” coral Pocillopora damicornis in the western Philippine archipelago](https://link.springer.com/article/10.1007/s00338-018-1729-3)

* [A simple molecular technique for distinguishing species reveals frequent misidentification of Hawaiian corals in the genus Pocillopora](https://peerj.com/articles/4355/) 

* [With eyes wide open: a revision of species within and closely related to the Pocillopora damicornis species complex (Scleractinia; Pocilloporidae) using morphology and genetics](https://onlinelibrary.wiley.com/doi/abs/10.1111/zoj.12092)

* [A genomic glance through the fog of plasticity and diversification in Pocillopora](https://www.nature.com/articles/s41598-017-06085-3)

* [Comparative analysis of the Pocillopora damicornis genome highlights role of immune system in coral evolution](https://www.nature.com/articles/s41598-018-34459-8)

* [Genome of the Cauliflower Coral Pocillopora verrucosa](https://academic.oup.com/gbe/article/12/10/1911/5898631)

* [Switch between Morphospecies of Pocillopora Corals](https://www.journals.uchicago.edu/doi/full/10.1086/682363)

* [Molecular assessment of Pocillopora verrucosa (Scleractinia; Pocilloporidae) distribution along a depth gradient in Ludao, Taiwan](https://peerj.com/articles/5797/)

* [Niche differences in co-occurring cryptic coral species (Pocillopora spp.)](https://link.springer.com/article/10.1007/s00338-021-02107-9)

* [Response diversity in corals: hidden differences in bleaching mortality among cryptic Pocillopora species](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.3324)

* [Solving the Coral Species Delimitation Conundrum](https://academic.oup.com/sysbio/article/71/2/461/6372710?login=true)

***

### Eastern Tropical Pacific coral biodiversity and biogeographic patterns 
*links being added*

* [A biogeographic analysis and review of the far eastern Pacific coral reef region](https://link.springer.com/article/10.1007/s003380050220)

* [The Eastern Tropical Pacific coral population connectivity and the role of the Eastern Pacific Barrier](https://www.nature.com/articles/s41598-018-27644-2)

* [Coral reef resilience to thermal stress in the Eastern Tropical Pacific](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.15126)

***

### Coral conservation genetics and restoration references

* [A restoration genetics guide for coral reef conservation](https://doi.org/10.1111/j.1365-294X.2008.03787.x)

* [Considerations for maximizing the adaptive potential of restored coral populations in the western Atlantic](https://doi.org/10.1002/eap.1978)

* [A roadmap to integrating resilience into the practice of coral reef restoration](https://onlinelibrary.wiley.com/doi/10.1111/gcb.16212)

* [Translating the 10 golden rules of reforestation for coral reef restoration](https://doi.org/10.1111/cobi.13890)

* [Six priorities to advance the science and practice of coral reef restoration worldwide](https://onlinelibrary.wiley.com/doi/10.1111/rec.13498)\

* [Coral reef restoration for coastal protection: Crafting technical and financial solutions](https://doi.org/10.1016/j.jenvman.2022.114718)

***

### Referencias en español 
*links being added*

* [Arrecifes coralinos del Pacífico Oriental Tropical: Revisión y perspectivas](https://revistas.ucr.ac.cr/index.php/rbt/article/view/23961)

* [Los ecosistemas marinos del Pacífico sur de Costa Rica: estado del conocimiento y perspectivas de manejo](https://revistas.ucr.ac.cr/index.php/rbt/article/view/26832)

* [Comunidades coralinas y arrecifes del Área de Conservación Guanacaste, Costa Rica](https://revistas.ucr.ac.cr/index.php/rbt/article/view/30925)

* [Distribución potencial bajo escenarios de cambio climático de corales del género Pocillopora (Anthozoa: Scleractinia) en el Pacífico oriental tropical](http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1870-34532019000100613)

***

[Link](https://drive.google.com/drive/folders/1PocOnMVBMGDKY8HEK23zvLB95Mn1WhuH?usp=sharing) to Google Drive folder with paper PDFs
