---
title: "Resources"
output:
   html_document:
    toc: true
    code_folding: null
    number_sections: false
    theme: "cerulean"
---

***

### Resources for learning fundamentals of genetics, evolution, and conservation genomics
*currently being added*  

* [Molecular Biology | Fundamentals of Biology - MIT OpenCourseWare](https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/pages/molecular-biology/)
* [Genetics | Fundamentals of Biology - MIT OpenCourseWare](https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/pages/genetics/)
* [NIH Genomics Education Websites](https://www.genome.gov/about-genomics/teaching-tools/Genomics-Education-Websites)
* [DNA from the Beginning](http://dnaftb.org/)
* [Molecular Biology of the Cell, 4th ed.](https://www.ncbi.nlm.nih.gov/books/NBK21054/) NCBI Bookshelf
* [Introduction to Conservation Genetics, 2nd ed.](https://books.google.com/books?id=BucgAwAAQBAJ) Google Books

***

### Resources for learning about DNA extraction and molecular biology laboratory techniques
*currently being added*  

* [Genetics Learning Resources](https://www.jax.org/education-and-learning/high-school-students-and-undergraduates/teaching-the-genome-generation/stem-learning-resources)
* [CDC Laboratory Training: Basic Molecular Biology](https://www.cdc.gov/labtraining/training-courses/basic-molecular-biology/index.html)
* [Integrated DNA Technologies (IDT) Education Pages](https://www.idtdna.com/pages/education/)
* [IDT Genotyping: Terms to Know](https://www.idtdna.com/pages/education/decoded/article/genotyping-terms-to-know)

***

### Resources and links for starting bioinformatics 

* Practice exercises from the Software Carpentries: [Unix command line](https://swcarpentry.github.io/shell-novice/)
* Install [R](https://www.r-project.org/) and [RStudio](https://www.rstudio.com/products/rstudio/download/)
* Practice exercises in Software Carpentries: [Programming in R](http://swcarpentry.github.io/r-novice-inflammation/)
* Install the R packages in the [tidyverse](https://www.tidyverse.org/), explore making plots with [ggplot2](https://ggplot2.tidyverse.org/) 
* Explore the [R graph gallery website](https://r-graph-gallery.com/)
* Start practicing the exercises in the [R for Data Science](https://r4ds.had.co.nz/) book 
* Practice exercises in [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) book 
* Create a [GitHub](https://github.com/) account and make your first repository 
* Follow the beginner [Git tutorials](https://swcarpentry.github.io/git-novice/) for Software Carpentries
* Begin using [RMarkdown](https://rmarkdown.rstudio.com/) and create an [R notebook for making simple plots](https://rmarkdown.rstudio.com/lesson-10.html)

#### Additional Software resources

* MEGA ([Link](https://www.megasoftware.net/)) - Molecular Evolutionary Genetics Analysis (MEGA) software
* R packages
    + [tidyverse](https://cran.r-project.org/web/packages/tidyverse/index.html) and [tidyverse homepage](https://www.tidyverse.org/)
    + [ape](https://cran.r-project.org/web/packages/ape/index.html) and [ape homepage](http://ape-package.ird.fr/)
    + [adegenet](https://cran.r-project.org/web/packages/adegenet/index.html) and [adegenet homepage](https://adegenet.r-forge.r-project.org/)
    + [pegas](https://cran.r-project.org/web/packages/pegas/index.html)
    + [poppr](https://cran.r-project.org/web/packages/poppr/index.html) and [poppr homepage](https://grunwaldlab.github.io/poppr/)
* PHYLUCE ([Link](https://phyluce.readthedocs.io/en/latest/))
* samtools ([Link](http://www.htslib.org/))
* IQ-TREE ([Link](http://www.iqtree.org/))
* RAxML ([Link](https://cme.h-its.org/exelixis/web/software/raxml/))
* BEAST2 ([Link](https://www.beast2.org/))

***

### Recursos en español

Software Carpentry lecciones en español  

* [La Terminal de Unix](https://swcarpentry.github.io/shell-novice-es/)  
* [El Control de Versiones con Git](https://swcarpentry.github.io/git-novice-es/)  
* [R para Análisis Científicos Reproducibles](https://swcarpentry.github.io/r-novice-gapminder-es/)  

